# TODO: Set base image
# Use ollama/ollama:latest

# TODO: Set environment variables
# Set OLLAMA_HOST, OLLAMA_MODELS, OLLAMA_DEBUG, OLLAMA_KEEP_ALIVE

# TODO: Download model into container image
# Set MODEL variable and pull the model during build

# TODO: Set startup command
# Use ENTRYPOINT to run ollama serve
